export interface Product {
  id: string
  name: string
  brand: string
  category: string
  power: number
  capacity: number
  price: number
  description: string
  image: string
  stock: number
  createdAt: string
  isNew?: boolean
  isPopular?: boolean
}

export const brands = [
  "EcoFlow",
  "Bluetti",
  "Jackery",
  "Anker",
  "Goal Zero",
  "Oukitel",
  "Allpowers",
  "Zendure",
] as const

export const categories = [
  "Портативні станції",
  "Сонячні панелі",
  "Комплекти",
  "Акумулятори",
  "Аксесуари",
] as const

export const products: Product[] = [
  // EcoFlow
  {
    id: "eco-1",
    name: "EcoFlow RIVER 2",
    brand: "EcoFlow",
    category: "Портативні станції",
    power: 300,
    capacity: 256,
    price: 8999,
    description:
      "Компактна зарядна станція EcoFlow RIVER 2 з потужністю 300 Вт та ємністю 256 Вт·год. Ідеальна для подорожей, кемпінгу та резервного живлення. Підтримує швидку зарядку за 60 хвилин завдяки технології X-Stream.",
    image: "/products/ecoflow-river-2.jpg",
    stock: 25,
    createdAt: "2025-12-01",
    isPopular: true,
  },
  {
    id: "eco-2",
    name: "EcoFlow RIVER 2 Max",
    brand: "EcoFlow",
    category: "Портативні станції",
    power: 500,
    capacity: 512,
    price: 16499,
    description:
      "EcoFlow RIVER 2 Max з потужністю 500 Вт та ємністю 512 Вт·год. Розширена версія RIVER 2 з більшою ємністю та потужністю для довготривалого використання.",
    image: "/products/ecoflow-river-2-max.jpg",
    stock: 18,
    createdAt: "2025-12-15",
    isNew: true,
  },
  {
    id: "eco-3",
    name: "EcoFlow DELTA 2",
    brand: "EcoFlow",
    category: "Портативні станції",
    power: 1800,
    capacity: 1024,
    price: 37999,
    description:
      "Потужна зарядна станція EcoFlow DELTA 2 з потужністю 1800 Вт та ємністю 1024 Вт·год. Забезпечує живлення для більшості побутових приладів.",
    image: "/products/ecoflow-delta-2.jpg",
    stock: 12,
    createdAt: "2025-11-01",
    isPopular: true,
  },
  {
    id: "eco-4",
    name: "EcoFlow DELTA Pro",
    brand: "EcoFlow",
    category: "Портативні станції",
    power: 3600,
    capacity: 3600,
    price: 99999,
    description:
      "Найпотужніша портативна станція EcoFlow DELTA Pro з потужністю 3600 Вт та ємністю 3600 Вт·год. Розширюється до 25 кВт·год.",
    image: "/products/ecoflow-delta-pro.jpg",
    stock: 5,
    createdAt: "2025-10-01",
    isPopular: true,
  },
  {
    id: "eco-5",
    name: "EcoFlow 220W Сонячна панель",
    brand: "EcoFlow",
    category: "Сонячні панелі",
    power: 220,
    capacity: 0,
    price: 18999,
    description:
      "Портативна складна сонячна панель EcoFlow потужністю 220 Вт. Водостійка конструкція IP68 з ефективністю конвертації до 23%.",
    image: "/products/ecoflow-solar-220.jpg",
    stock: 30,
    createdAt: "2026-01-10",
    isNew: true,
  },
  {
    id: "eco-6",
    name: "EcoFlow RIVER 2 + Панель 110W",
    brand: "EcoFlow",
    category: "Комплекти",
    power: 300,
    capacity: 256,
    price: 14999,
    description:
      "Комплект: зарядна станція EcoFlow RIVER 2 та сонячна панель 110 Вт. Повне рішення для автономного живлення на природі.",
    image: "/products/ecoflow-kit.jpg",
    stock: 10,
    createdAt: "2026-01-20",
    isNew: true,
  },
  // Bluetti
  {
    id: "blu-1",
    name: "Bluetti EB3A",
    brand: "Bluetti",
    category: "Портативні станції",
    power: 600,
    capacity: 268,
    price: 9499,
    description:
      "Компактна зарядна станція Bluetti EB3A з потужністю 600 Вт та ємністю 268 Вт·год. LiFePO4 батарея з терміном служби 2500+ циклів.",
    image: "/products/bluetti-eb3a.jpg",
    stock: 22,
    createdAt: "2025-11-15",
    isPopular: true,
  },
  {
    id: "blu-2",
    name: "Bluetti AC200P",
    brand: "Bluetti",
    category: "Портативні станції",
    power: 2000,
    capacity: 2000,
    price: 52999,
    description:
      "Потужна зарядна станція Bluetti AC200P з потужністю 2000 Вт та ємністю 2000 Вт·год. 17 вихідних портів для різних пристроїв.",
    image: "/products/bluetti-ac200p.jpg",
    stock: 8,
    createdAt: "2025-10-20",
    isPopular: true,
  },
  {
    id: "blu-3",
    name: "Bluetti AC180",
    brand: "Bluetti",
    category: "Портативні станції",
    power: 1800,
    capacity: 1152,
    price: 39999,
    description:
      "Bluetti AC180 з потужністю 1800 Вт та ємністю 1152 Вт·год. Турбо зарядка за 45 хвилин до 80%.",
    image: "/products/bluetti-ac180.jpg",
    stock: 15,
    createdAt: "2026-01-05",
    isNew: true,
  },
  {
    id: "blu-4",
    name: "Bluetti PV200 Сонячна панель",
    brand: "Bluetti",
    category: "Сонячні панелі",
    power: 200,
    capacity: 0,
    price: 15999,
    description:
      "Портативна сонячна панель Bluetti PV200 потужністю 200 Вт з монокристалічними елементами та ефективністю до 23.4%.",
    image: "/products/bluetti-pv200.jpg",
    stock: 20,
    createdAt: "2025-12-10",
  },
  {
    id: "blu-5",
    name: "Bluetti B230 Акумулятор",
    brand: "Bluetti",
    category: "Акумулятори",
    power: 0,
    capacity: 2048,
    price: 27999,
    description:
      "Додатковий акумулятор Bluetti B230 ємністю 2048 Вт·год для розширення станцій серії AC200/AC300.",
    image: "/products/bluetti-b230.jpg",
    stock: 12,
    createdAt: "2025-11-20",
  },
  // Jackery
  {
    id: "jac-1",
    name: "Jackery Explorer 300",
    brand: "Jackery",
    category: "Портативні станції",
    power: 300,
    capacity: 293,
    price: 7999,
    description:
      "Легка зарядна станція Jackery Explorer 300 з потужністю 300 Вт та ємністю 293 Вт·год. Вага лише 3.2 кг.",
    image: "/products/jackery-300.jpg",
    stock: 35,
    createdAt: "2025-12-05",
    isPopular: true,
  },
  {
    id: "jac-2",
    name: "Jackery Explorer 1000 Pro",
    brand: "Jackery",
    category: "Портативні станції",
    power: 1000,
    capacity: 1002,
    price: 32999,
    description:
      "Jackery Explorer 1000 Pro з потужністю 1000 Вт та ємністю 1002 Вт·год. Зарядка від сонця за 1.8 години.",
    image: "/products/jackery-1000-pro.jpg",
    stock: 10,
    createdAt: "2025-11-25",
    isPopular: true,
  },
  {
    id: "jac-3",
    name: "Jackery Explorer 2000 Plus",
    brand: "Jackery",
    category: "Портативні станції",
    power: 3000,
    capacity: 2042,
    price: 65999,
    description:
      "Jackery Explorer 2000 Plus з потужністю 3000 Вт та ємністю 2042 Вт·год. Розширюється до 12 кВт·год за допомогою додаткових батарей.",
    image: "/products/jackery-2000-plus.jpg",
    stock: 6,
    createdAt: "2026-02-01",
    isNew: true,
  },
  {
    id: "jac-4",
    name: "Jackery SolarSaga 200W",
    brand: "Jackery",
    category: "Сонячні панелі",
    power: 200,
    capacity: 0,
    price: 14499,
    description:
      "Портативна сонячна панель Jackery SolarSaga 200 Вт з водостійким корпусом IP65 та ефективністю 24.3%.",
    image: "/products/jackery-solar-200.jpg",
    stock: 25,
    createdAt: "2025-12-20",
  },
  {
    id: "jac-5",
    name: "Jackery Explorer 1000 + SolarSaga 100W",
    brand: "Jackery",
    category: "Комплекти",
    power: 1000,
    capacity: 1002,
    price: 37999,
    description:
      "Комплект Jackery Solar Generator 1000: станція Explorer 1000 та сонячна панель SolarSaga 100 Вт.",
    image: "/products/jackery-kit-1000.jpg",
    stock: 8,
    createdAt: "2026-01-15",
    isNew: true,
  },
  // Anker
  {
    id: "ank-1",
    name: "Anker SOLIX C300",
    brand: "Anker",
    category: "Портативні станції",
    power: 300,
    capacity: 288,
    price: 8499,
    description:
      "Компактна зарядна станція Anker SOLIX C300 з потужністю 300 Вт та ємністю 288 Вт·год. Технологія InfiniPower для тривалої роботи.",
    image: "/products/anker-c300.jpg",
    stock: 28,
    createdAt: "2025-12-08",
  },
  {
    id: "ank-2",
    name: "Anker SOLIX C1000",
    brand: "Anker",
    category: "Портативні станції",
    power: 1056,
    capacity: 1056,
    price: 29999,
    description:
      "Anker SOLIX C1000 з потужністю 1056 Вт та ємністю 1056 Вт·год. Зарядка від 0 до 100% за 58 хвилин через HyperFlash.",
    image: "/products/anker-c1000.jpg",
    stock: 14,
    createdAt: "2025-11-10",
    isPopular: true,
  },
  {
    id: "ank-3",
    name: "Anker SOLIX F3800",
    brand: "Anker",
    category: "Портативні станції",
    power: 6000,
    capacity: 3840,
    price: 109999,
    description:
      "Найпотужніша станція Anker SOLIX F3800 з потужністю 6000 Вт та ємністю 3840 Вт·год. Живить весь будинок.",
    image: "/products/anker-f3800.jpg",
    stock: 3,
    createdAt: "2026-02-10",
    isNew: true,
  },
  {
    id: "ank-4",
    name: "Anker 625 Сонячна панель 100W",
    brand: "Anker",
    category: "Сонячні панелі",
    power: 100,
    capacity: 0,
    price: 7999,
    description:
      "Портативна сонячна панель Anker 625 потужністю 100 Вт. Легка та складна конструкція для походів.",
    image: "/products/anker-solar-100.jpg",
    stock: 40,
    createdAt: "2025-12-12",
  },
  {
    id: "ank-5",
    name: "Anker SOLIX C1000 + Панель 200W",
    brand: "Anker",
    category: "Комплекти",
    power: 1056,
    capacity: 1056,
    price: 39999,
    description:
      "Комплект: зарядна станція Anker SOLIX C1000 та сонячна панель 200 Вт. Оптимальне рішення для заміського відпочинку.",
    image: "/products/anker-kit-c1000.jpg",
    stock: 7,
    createdAt: "2026-01-25",
    isNew: true,
  },
  // Goal Zero
  {
    id: "gz-1",
    name: "Goal Zero Yeti 500X",
    brand: "Goal Zero",
    category: "Портативні станції",
    power: 500,
    capacity: 505,
    price: 18999,
    description:
      "Зарядна станція Goal Zero Yeti 500X з потужністю 500 Вт та ємністю 505 Вт·год. Легендарна якість та надійність.",
    image: "/products/gz-yeti-500x.jpg",
    stock: 16,
    createdAt: "2025-11-05",
  },
  {
    id: "gz-2",
    name: "Goal Zero Yeti 1500X",
    brand: "Goal Zero",
    category: "Портативні станції",
    power: 2000,
    capacity: 1516,
    price: 54999,
    description:
      "Goal Zero Yeti 1500X з потужністю 2000 Вт та ємністю 1516 Вт·год. Преміальна портативна електростанція.",
    image: "/products/gz-yeti-1500x.jpg",
    stock: 7,
    createdAt: "2025-10-15",
    isPopular: true,
  },
  {
    id: "gz-3",
    name: "Goal Zero Yeti 3000X",
    brand: "Goal Zero",
    category: "Портативні станції",
    power: 3000,
    capacity: 2982,
    price: 89999,
    description:
      "Топова станція Goal Zero Yeti 3000X з потужністю 3000 Вт та ємністю 2982 Вт·год.",
    image: "/products/gz-yeti-3000x.jpg",
    stock: 4,
    createdAt: "2026-01-30",
    isNew: true,
  },
  {
    id: "gz-4",
    name: "Goal Zero Nomad 200 Сонячна панель",
    brand: "Goal Zero",
    category: "Сонячні панелі",
    power: 200,
    capacity: 0,
    price: 19999,
    description:
      "Преміальна складна сонячна панель Goal Zero Nomad 200 з потужністю 200 Вт та високою ефективністю.",
    image: "/products/gz-nomad-200.jpg",
    stock: 15,
    createdAt: "2025-12-25",
  },
  // Oukitel
  {
    id: "ouk-1",
    name: "Oukitel P501",
    brand: "Oukitel",
    category: "Портативні станції",
    power: 500,
    capacity: 505,
    price: 9999,
    description:
      "Доступна зарядна станція Oukitel P501 з потужністю 500 Вт та ємністю 505 Вт·год. Відмінне співвідношення ціна/якість.",
    image: "/products/oukitel-p501.jpg",
    stock: 30,
    createdAt: "2025-12-03",
  },
  {
    id: "ouk-2",
    name: "Oukitel P1201",
    brand: "Oukitel",
    category: "Портативні станції",
    power: 1200,
    capacity: 960,
    price: 24999,
    description:
      "Oukitel P1201 з потужністю 1200 Вт та ємністю 960 Вт·год. LiFePO4 батарея з 3500 циклами зарядки.",
    image: "/products/oukitel-p1201.jpg",
    stock: 18,
    createdAt: "2025-11-28",
  },
  {
    id: "ouk-3",
    name: "Oukitel P2001",
    brand: "Oukitel",
    category: "Портативні станції",
    power: 2000,
    capacity: 2000,
    price: 45999,
    description:
      "Потужна станція Oukitel P2001 з потужністю 2000 Вт та ємністю 2000 Вт·год. UPS функція для безперебійного живлення.",
    image: "/products/oukitel-p2001.jpg",
    stock: 9,
    createdAt: "2026-02-05",
    isNew: true,
  },
  {
    id: "ouk-4",
    name: "Oukitel PV200 Сонячна панель",
    brand: "Oukitel",
    category: "Сонячні панелі",
    power: 200,
    capacity: 0,
    price: 10999,
    description:
      "Доступна сонячна панель Oukitel PV200 потужністю 200 Вт з ефективністю 21.5%.",
    image: "/products/oukitel-pv200.jpg",
    stock: 25,
    createdAt: "2025-12-18",
  },
  {
    id: "ouk-5",
    name: "Oukitel BP2000 Акумулятор",
    brand: "Oukitel",
    category: "Акумулятори",
    power: 0,
    capacity: 2048,
    price: 22999,
    description:
      "Додатковий акумулятор Oukitel BP2000 ємністю 2048 Вт·год для розширення станцій Oukitel P2001.",
    image: "/products/oukitel-bp2000.jpg",
    stock: 14,
    createdAt: "2025-11-30",
  },
  // Allpowers
  {
    id: "all-1",
    name: "Allpowers R600",
    brand: "Allpowers",
    category: "Портативні станції",
    power: 600,
    capacity: 299,
    price: 7499,
    description:
      "Бюджетна зарядна станція Allpowers R600 з потужністю 600 Вт та ємністю 299 Вт·год. LiFePO4 батарея.",
    image: "/products/allpowers-r600.jpg",
    stock: 40,
    createdAt: "2025-12-02",
  },
  {
    id: "all-2",
    name: "Allpowers S1500",
    brand: "Allpowers",
    category: "Портативні станції",
    power: 1500,
    capacity: 1092,
    price: 29999,
    description:
      "Allpowers S1500 з потужністю 1500 Вт та ємністю 1092 Вт·год. 15 вихідних портів для будь-яких потреб.",
    image: "/products/allpowers-s1500.jpg",
    stock: 12,
    createdAt: "2025-11-18",
  },
  {
    id: "all-3",
    name: "Allpowers S2000 Pro",
    brand: "Allpowers",
    category: "Портативні станції",
    power: 2400,
    capacity: 2016,
    price: 49999,
    description:
      "Allpowers S2000 Pro з потужністю 2400 Вт та ємністю 2016 Вт·год. Має вбудований WiFi для моніторингу через додаток.",
    image: "/products/allpowers-s2000-pro.jpg",
    stock: 7,
    createdAt: "2026-01-08",
    isNew: true,
  },
  {
    id: "all-4",
    name: "Allpowers SP033 200W Панель",
    brand: "Allpowers",
    category: "Сонячні панелі",
    power: 200,
    capacity: 0,
    price: 11999,
    description:
      "Складна сонячна панель Allpowers SP033 потужністю 200 Вт. Сумісна з більшістю зарядних станцій.",
    image: "/products/allpowers-sp033.jpg",
    stock: 22,
    createdAt: "2025-12-22",
  },
  {
    id: "all-5",
    name: "Allpowers S2000 + SP033 200W",
    brand: "Allpowers",
    category: "Комплекти",
    power: 2400,
    capacity: 2016,
    price: 55999,
    description:
      "Комплект: станція Allpowers S2000 Pro та сонячна панель SP033 200 Вт. Повна автономія.",
    image: "/products/allpowers-kit.jpg",
    stock: 5,
    createdAt: "2026-02-12",
    isNew: true,
  },
  // Zendure
  {
    id: "zen-1",
    name: "Zendure SuperBase V4600",
    brand: "Zendure",
    category: "Портативні станції",
    power: 3800,
    capacity: 4608,
    price: 119999,
    description:
      "Преміальна станція Zendure SuperBase V4600 з потужністю 3800 Вт та ємністю 4608 Вт·год. Напівтвердотільна батарея нового покоління.",
    image: "/products/zendure-v4600.jpg",
    stock: 3,
    createdAt: "2026-02-15",
    isNew: true,
  },
  {
    id: "zen-2",
    name: "Zendure SuperBase 600M",
    brand: "Zendure",
    category: "Портативні станції",
    power: 600,
    capacity: 607,
    price: 17999,
    description:
      "Zendure SuperBase 600M з потужністю 600 Вт та ємністю 607 Вт·год. Компактний дизайн для подорожей.",
    image: "/products/zendure-600m.jpg",
    stock: 20,
    createdAt: "2025-11-22",
  },
  {
    id: "zen-3",
    name: "Zendure SuperBase Pro 2000",
    brand: "Zendure",
    category: "Портативні станції",
    power: 2000,
    capacity: 2096,
    price: 59999,
    description:
      "Zendure SuperBase Pro 2000 з потужністю 2000 Вт та ємністю 2096 Вт·год. Промисловий дизайн з колесами.",
    image: "/products/zendure-pro-2000.jpg",
    stock: 6,
    createdAt: "2025-10-25",
  },
  {
    id: "zen-4",
    name: "Zendure 200W Сонячна панель",
    brand: "Zendure",
    category: "Сонячні панелі",
    power: 200,
    capacity: 0,
    price: 16999,
    description:
      "Преміальна сонячна панель Zendure потужністю 200 Вт з ETFE покриттям та IP67 захистом.",
    image: "/products/zendure-solar-200.jpg",
    stock: 18,
    createdAt: "2025-12-28",
  },
  {
    id: "zen-5",
    name: "Zendure SuperBase V + Панель 400W",
    brand: "Zendure",
    category: "Комплекти",
    power: 3800,
    capacity: 4608,
    price: 134999,
    description:
      "Преміальний комплект: Zendure SuperBase V4600 та сонячна панель 400 Вт. Максимальна автономія.",
    image: "/products/zendure-kit-v.jpg",
    stock: 2,
    createdAt: "2026-02-18",
    isNew: true,
  },
  // Additional accessories
  {
    id: "acc-1",
    name: "EcoFlow Кабель для автомобіля",
    brand: "EcoFlow",
    category: "Аксесуари",
    power: 0,
    capacity: 0,
    price: 1499,
    description:
      "Автомобільний зарядний кабель для зарядних станцій EcoFlow. Довжина 1.5 м, сумісний з RIVER та DELTA серіями.",
    image: "/products/ecoflow-car-cable.jpg",
    stock: 50,
    createdAt: "2025-12-30",
  },
  {
    id: "acc-2",
    name: "Bluetti Сумка для переносу",
    brand: "Bluetti",
    category: "Аксесуари",
    power: 0,
    capacity: 0,
    price: 2499,
    description:
      "Захисна сумка для переносу зарядних станцій Bluetti. Водостійкий матеріал з м'якою підкладкою.",
    image: "/products/bluetti-bag.jpg",
    stock: 35,
    createdAt: "2025-12-15",
  },
  {
    id: "acc-3",
    name: "Jackery Адаптер Anderson",
    brand: "Jackery",
    category: "Аксесуари",
    power: 0,
    capacity: 0,
    price: 999,
    description:
      "Адаптер Anderson для підключення сонячних панелей до зарядних станцій Jackery.",
    image: "/products/jackery-adapter.jpg",
    stock: 60,
    createdAt: "2025-11-10",
  },
  {
    id: "acc-4",
    name: "Allpowers Подовжувач MC4",
    brand: "Allpowers",
    category: "Аксесуари",
    power: 0,
    capacity: 0,
    price: 799,
    description:
      "MC4 подовжувач 5 метрів для сонячних панелей. Сумісний з усіма брендами.",
    image: "/products/allpowers-mc4.jpg",
    stock: 45,
    createdAt: "2025-12-05",
  },
  {
    id: "acc-5",
    name: "Goal Zero Yeti Link Модуль",
    brand: "Goal Zero",
    category: "Аксесуари",
    power: 0,
    capacity: 0,
    price: 3999,
    description:
      "Модуль розширення Goal Zero Yeti Link для об'єднання кількох станцій Yeti в одну систему.",
    image: "/products/gz-link-module.jpg",
    stock: 10,
    createdAt: "2026-01-02",
  },
]

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getPopularProducts(): Product[] {
  return products.filter((p) => p.isPopular)
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew)
}

export function formatPrice(price: number): string {
  return price.toLocaleString("uk-UA") + " \u20B4"
}
